services:
  ms-tracker-db:
    image: postgres:16-alpine
    container_name: ms-tracker-db
    environment:
      POSTGRES_USER: ms_tracker
      POSTGRES_PASSWORD: ms_tracker_secret
      POSTGRES_DB: ms_tracker_db
    ports:
      - "5432:5432"
    volumes:
      - ms-tracker-db-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ms_tracker -d ms_tracker_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  ms-tracker-db-data:
    driver: local
